#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "build src/group.ls -> dist/index.js ..."
./node_modules/.bin/lsc -cbp src/group.ls > dist/index.js
echo "build src/parse-path.ls -> dist/index.js ..."
./node_modules/.bin/lsc -cbp src/parse-path.ls >> dist/index.js
echo "minifying parse-path.js ..."
./node_modules/.bin/uglifyjs dist/index.js > dist/index.min.js
echo "done."

